### ISSUE TITLE
DISPAY vs DISPLAY in parser.py

### ISSUE THREAD

**Issue by donnels** [pschatzmann/jupyter-openscad-kernel#6]
os.environ['DISPAY'] 
on line 224  should proabbly be DISPLAY?

**Comment by donnels** [comment]
also:
should line 180 read differently? (applicatioin vs application)
def mimeToExtension(self, mime):
        list = mime.split("/")
        if len(list)!=2:
            raise Exception('Invalid mime type: {}'.format(mime))
        result = list[1]
        if mime=="text/plain":
            result = "txt"
        if mime=="applicatioin/openscad":
            result = "txt"
        return result

**Comment by pschatzmann** [comment]
Thanks for your input. The corrections have been deployed now
